##Exchange file path
API_EXCHANGE_ASSET_FILE_PATH: 
## Local Exchange assert information
API_EXCHANGE_ASSET_ID : 
API_EXCHANGE_ASSET_VERSION : 
EXCHANGE_ASSET_NAME:

## API instance name
API_INSTANCE_LABEL_NAME : 

#API_INSTANCE_POLICIES : 
#POLICY_CROS_ORIGINS : 