## SERVER properties , ARM_SERVER_NAME can be server /cluster/ server group
ARM_SERVER_NAME :

#Application information
APPLICATION_NAME :

EXCHANGE_ASSET_ID:
EXCHANGE_ASSET_VERSION:

applicationProperties :
    <key1>: <value1>
    <key2>: <value2>
