---
- hosts: "{{ api }}"
  roles:
  - { role: windows/jda_mule_api_with_asset, when: ansible_connection is defined and ansible_connection == 'winrm'}
  - { role: linux/jda_mule_api_with_asset, when: ansible_connection is undefined or ansible_connection != 'winrm'}