---
- hosts: "{{ config }}"
  roles:
  - { role: windows/jda_exchange_asset, when: ansible_connection is defined and ansible_connection == 'winrm' and EXCHANGE_ASSET_ID is defined}
  - { role: linux/jda_exchange_asset, when: ansible_connection is undefined or ansible_connection != 'winrm' and EXCHANGE_ASSET_ID is defined}
  - { role: windows/cps_ConfigurationPublish, when: ansible_connection is defined and ansible_connection == 'winrm'}
  - { role: linux/cps_ConfigurationPublish, when: ansible_connection is undefined or ansible_connection != 'winrm'}