---
- hosts: "{{ asset }}"
  roles:
  - { role: windows/jda_exchange_asset, when: ansible_connection is defined and ansible_connection == 'winrm'}
  - { role: linux/jda_exchange_asset, when: ansible_connection is undefined or ansible_connection != 'winrm'}