---
- hosts: "{{ cluster }}"
  roles:
  - { role: windows/jda_cluster, when: ansible_connection is defined and ansible_connection == 'winrm'}
  - { role: linux/jda_cluster, when: ansible_connection is undefined or ansible_connection != 'winrm'}