---
- hosts: "{{ application }}"
  roles:
  - { role: windows/jda_application_deploy_with_asset, when: ansible_connection is defined and ansible_connection == 'winrm'}
  - { role: linux/jda_application_deploy_with_asset, when: ansible_connection is undefined or ansible_connection != 'winrm'}