---
- name: Set properties
  set_fact:
    scriptsLocation: "{{ansible_env.HOME}}/temp_connect_dir/server_{{ARM_SERVER_NAME}}"
    className: 'com.jda.jci.installer.MRTInstaller'
  tags:
    - propertyFile
    - install
    - action
    - setup
    - clean
##Cleanup
- name: Cleanup
  block:   
    - name: Check directory
      stat:
        path: "{{scriptsLocation}}"
      register: mrt_install_location

    - name: Delete scripts if existed in target location
      file:
        state: absent
        path: "{{scriptsLocation}}"
      when: mrt_install_location.stat.exists
  tags:
    - clean
    
##Transfer scripts/files into remote loction
- name: Transfer files and setup scripts 
  block:   
    - name: Create directory
      file:
        path: "{{scriptsLocation}}"
        state: directory

    - name: Unzipping {{ MRT_INSTALL_LOCATION }}/{{ INSTALL_ZIP_NAME }}  into remote install location
      unarchive:
        src: "{{ MRT_INSTALL_LOCATION }}/{{ INSTALL_ZIP_NAME }}"
        dest: "{{scriptsLocation}}/"       

    - name: Copy {{ SOURCE_KEY_STORE_PATH }} into remote location
      copy:
        src: "{{ SOURCE_KEY_STORE_PATH }}"
        dest: "{{scriptsLocation}}/"
      when : SOURCE_KEY_STORE_PATH is defined and SOURCE_KEY_STORE_PATH != ""
  tags:
    - setup
##Property file setup 
- name: Silent install property creation
  block:
    - name: Delete silent-installer.properties
      file:
        state: absent
        path: "{{scriptsLocation}}/silent-installer.properties"
    - name: Create properties file
      file:
        path: "{{scriptsLocation}}/silent-installer.properties"
        state: touch

    - name: Add values into silent-installer.properties in remote installer location
      lineinfile: 
        dest: "{{scriptsLocation}}/silent-installer.properties"
        line: '{{ item }}'
      with_items:
        - 'ARM_INSTALLATION={{ ARM_INSTALLATION }}'
        - 'EU_COUNTRY={{ EU_COUNTRY }}'
        - 'ANYPOINT_USER_NAME={{ANYPOINT_USER_NAME }}'
        - 'ANYPOINT_USER_PASSWORD={{ ANYPOINT_USER_PASSWORD}}'
        - 'BUSINESS_GROUP={{BUSINESS_GROUP }}'
        - 'ARM_ENVIRONMENT_NAME={{ ARM_ENVIRONMENT_NAME}}'
        - 'ARM_SERVER_NAME={{ARM_SERVER_NAME }}'
        - 'HOST_NAME={{HOST_NAME }}'
        - 'INSTALL_LOCATION={{ INSTALL_LOCATION}}'

    - name: Add AES_SECRET values into silent-installer.properties in remote installer location
      lineinfile: 
        dest: "{{scriptsLocation}}/silent-installer.properties"
        line: '{{ item }}'
      with_items:
        - 'AES_SECRET_KEY_STORE_PATH={{ AES_SECRET_KEY_STORE_PATH }}'
        - 'AES_SECRET_KEY_STORE_PASSWORD={{AES_SECRET_KEY_STORE_PASSWORD }}'
        - 'AES_SECRET_KEY_ALIAS={{AES_SECRET_KEY_ALIAS }}'
        - 'AES_SECRET_KEY_PASSWORD={{ AES_SECRET_KEY_PASSWORD}}'
      when : SOURCE_KEY_STORE_PATH is defined and SOURCE_KEY_STORE_PATH != ""


    - name: Add wrapper properties into silent-installer.properties in remote installer location
      lineinfile:
        dest: "{{scriptsLocation}}/jda-wrapper-additional.conf"
        line: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ serverProperties }}"
      when: serverProperties | default(false, true) and  serverProperties | trim != ''
  tags:
    - propertyFile    
##Script execution
- name: Script execution 
  block:
    - name: Set runtime arguments
      set_fact:
        arguments: ''
      when: server_action is undefined
    - name: Set runtime arguments action
      set_fact:
        arguments: '-{{server_action}}'
      when: server_action is defined
    - name: Set runtime arguments reinstall & backup
      set_fact:
        arguments: '-reinstall -backup'
      when: server_action is defined and server_action == "reinstall,backup"

    - name: Set runtime arguments reinstall
      set_fact:
        arguments: '-reinstall'
      when: server_action is defined and server_action == "reinstall"
    - name: get install jar file name
      find:
        paths: "{{scriptsLocation}}"
        patterns: 'installation-assistance*'
      register: found_files
    - name: Set installJarName
      set_fact:
        installJarName: "{{ found_files.files[0].path | basename }}"
       
    - name: MRT Installation
      #command: "java -jar {{ installJarName }} -s silent-installer.properties {{arguments}}"
      command: "java -cp {{ installJarName }} {{className}} -s silent-installer.properties {{arguments}}"
      args:
        chdir: "{{scriptsLocation}}"
      register: output
    - debug:
        var: output.stdout_lines
  tags:
  - install
  - action

